apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: shareprocess
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - list
      - watch
      - create
      - update
      - delete