apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: shareprocess
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: shareprocess
subjects:
  - kind: ServiceAccount
    name: shareprocess
    namespace: kube-system